### PR TITLE
Update PunchOutOrderMessage.js to fix exception on missing shortname

### PR DESCRIPTION
**Pull request by dennismaxjung**
Changed item.name to be filled with description if no short name exists. Without this change it throws an exception.

Like the documentation:
image

### CODE REVIEW

**Comment by DPassarelli** [comment]
Hi Dennis,

Thank you so much for your contribution to this project! I'm glad you caught that bug. Since I've endeavored to maintain a full test suite on this project, I'd like to see a test case for this included somewhere...probably `PunchOutOrderMessage.spec.js`. That will prevent future regressions. Once that's included I'd be happy to review this for acceptance.

FYI...I'm currently working on a re-write of the internal implementation, and planning on releasing a new feature within the next couple of weeks. You are welcome to include a test case in this PR, or just wait a little while and I'll include one for the v1.1.0 update.

Thanks!
David

**Comment by dennismaxjung** [comment]
I've added the test case for the changed mapping of the description.
Based on your used js standard lint I've added some .vscode settings & extensions to benefit of auto formatting on save.

**Comment by dennismaxjung** [comment]
@DPassarelli I'm not sure why the ci build fails,..

**Comment by dennismaxjung** [comment]
@DPassarelli  From my perspective i've done what i could.
I'm ready for your review :-)

**Comment by DPassarelli** [comment]
Thank you for the extra effort! I will review this over the weekend.

**Comment by DPassarelli** [comment]
@dennismaxjung Thanks again for bringing this issue to my attention! It definitely needed to be fixed.

Instead of merging in your PR, however, I decided to add the fix to the codebase myself directly for the following reasons:

1. I'm not sure why your PR was failing on AppVeyor, but it was faster to for me to just incorporate the code changes on my end and keep the build working, rather than troubleshoot.
2. I appreciate that you added the necessary test case, but there was also a significant amount of "noise" in the commit due to formatting changes. I understand that that may have been done automatically by VSCode, but it makes it harder to focus in on what really changed.
3. I also appreciate that you enjoy using VSCode, but I prefer to keep my repos agnostic with regard to IDEs. I do not want to add unnecessary editor setting files since I think these tend to be specific (and unique) for each developer.

If your PRs could avoid whitespace changes in the future, then that would definitely make the review easier and faster.

NPM is now updated with v1.0.1 if you need to grab it for your project.

-David

**Pull request closed without merging**
